version: "1"
services:
  database:
    build: .
    container_name: generator-db
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: <>
      p: <>
    ports:
      - "3306:3306"
    mem_reservation: "10M"
    mem_limit: "250M"
  application:
    build: .
    container_name: generator
    image: dnd/generator:latest
    depends_on:
      - database
    environment:
      DB_PORT: <>
      DB_HOST: <>
      DB_USER: <>
      DB_PASSWORD: <>
      DB_NAME: <>
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    mem_reservation: "10M"
    mem_limit: "250M"